### ISSUE TITLE
Extension not compatible

### ISSUE THREAD

**Issue by melonn22** [dr0cx/vscode-ccltools-issue-tracking#1]
Hi, 
When I try to install this extension, it says it is not compatible with my version of VS. Can someone please help?

![image](https://github.com/user-attachments/assets/a698d9d8-64db-4b89-9a91-a86a7554fe58)

**Comment by dr0cx** [comment]
> Hi, When I try to install this extension, it says it is not compatible with my version of VS. Can someone please help?
> 
> ![image](https://private-user-images.githubusercontent.com/179966707/363296898-a698d9d8-64db-4b89-9a91-a86a7554fe58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTEzNjQsIm5iZiI6MTcyNTQxMTA2NCwicGF0aCI6Ii8xNzk5NjY3MDcvMzYzMjk2ODk4LWE2OThkOWQ4LTY0ZGItNGI4OS05YTkxLWE4NmE3NTU0ZmU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwMDUxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWNkNjk3NGFhOWVlMTkwMTNkMmYxMzc5ZTQxMzk2MGEwMzlhMWI2YTFkYTU5Y2M5ODZkMDY1ZGE0Mjg4YjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ieKtv3hxI2bn2LYd5kKcQi6wm_f5SmXbXu9N9vWMfp8)

The current version of VS Code is 1.92.2. Your version is from [August of 2020.]( https://code.visualstudio.com/updates/v1_49). My oldest release for this extension is December 08, 2021. Are you able to update VS Code?

**Comment by melonn22** [comment]
@dr0cx thanks for that. I suspected that was the issue but the only version I can download through my work organization was this old version. (I'm using a work laptop where admin access to install applications are limited). I was actually able to install the newest version through MS website (surprisingly) and it worked!
